services:
  postgres:
    image: postgres:16
    container_name: apex_karting
    environment:
      POSTGRES_USER: karting
      POSTGRES_PASSWORD: karting
      POSTGRES_DB: karting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
